name: Compile Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile:
    name: Compile ESP32 Firmware
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      
      - name: Install ESP32 core & libraries
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          # Install required libraries
          arduino-cli lib install "ESP32Servo"
          arduino-cli lib install "Adafruit BNO055"
          arduino-cli lib install "Adafruit Unified Sensor"
          arduino-cli lib install "Adafruit BusIO"
      
      - name: Compile sketch
        run: |
          # Compile the sketch in the firmware_monocopter folder
          arduino-cli compile --fqbn esp32:esp32:esp32 --warnings default --output-dir build firmware_monocopter
      
      - name: Show build outputs
        run: |
          echo "Build directory contents:"
          ls -la build/ || echo "Build directory not found"
          echo "Looking for .bin files:"
          find . -name "*.bin" -type f
      
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin
          if-no-files-found: warn
