name: Compile Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile:
    name: Compile ESP32 Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 core & libraries
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          # Libraries used by the sketch
          arduino-cli lib install "ESP32Servo" "Adafruit BNO055" "Adafruit Unified Sensor" "Adafruit BusIO"

      - name: Compile sketch (firmware_monocopter)
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir build firmware_monocopter

      - name: Show build outputs
        run: ls -la build || true

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin
