name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install dependencies
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          arduino-cli lib install "ESP32Servo" "Adafruit BNO055" "Adafruit Unified Sensor" "Adafruit BusIO"

      - name: Make sketch name match repo folder (Arduino requirement)
        run: |
          REPO_NAME="$(basename "$GITHUB_WORKSPACE")"
          if [ ! -f "$REPO_NAME.ino" ]; then
            cp Monocopter.ino "$REPO_NAME.ino"
          fi

      - name: Compile firmware
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir build .

      - name: Prepare release binary
        run: |
          mv build/*.bin monocopter-firmware-${{ github.ref_name }}.bin
          ls -la monocopter-firmware-*.bin

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: monocopter-firmware-*.bin
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
